
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-
namespace: dev-reviewfilmes

# - ./ingress.yaml
resources:
- ../base
- ./service.yaml
- ./postgre.yaml

images:
- name: placeholder
  newName: 216989136189.dkr.ecr.us-east-1.amazonaws.com/dev-review-filmes
  newTag: 24eb3d3

patches:
- path: replicas.yaml
- path: patch-db.yaml
