name: Pipeline CI 

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      image_tag:
        required: true
        type: string
    outputs:
      image_tag:
        description: "Tag curta da imagem gerada"
        value: ${{ jobs.ci.outputs.image_tag }}

permissions:
  contents: read
  id-token: write
  security-events: write
  packages: read

concurrency:
  group: ci-dev-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-testes:
    name: Testes unitários
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.0.300

      - name: Cache NuGet
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore
        working-directory: ./src
        run: dotnet restore Review-Filmes.sln

      - name: Testes unitários
        working-directory: ./src
        run: dotnet test ./Review-Filmes.Test.Unit/Review-Filmes.Test.Unit.csproj --no-restore --verbosity normal

  integration-testes:
    name: Testes de integração
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: review
          POSTGRES_PASSWORD: postgrespwd
          POSTGRES_DB: review-filmes
        ports:
          - 5432:5432


    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.0.300

      - name: Cache NuGet
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore
        working-directory: ./src
        run: dotnet restore Review-Filmes.sln

      - name: Testes de integração
        working-directory: ./src
        run: dotnet test ./Review-Filmes.Test.Integration/Review-Filmes.Test.Integration.csproj --no-restore --verbosity normal
        env:
          ConnectionStrings__DefaultConnection: "Host=localhost;Port=5432;Database=review-filmes;Username=review;Password=postgrespwd"

  # sonarqube:
  #   name: Análise SonarQube
  #   runs-on: ubuntu-latest
  #   environment: ${{ inputs.environment }}
  #   needs:
  #     - unit-testes
  #     - integration-testes

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0

  #     - name: Setup JDK
  #       uses: actions/setup-java@v4
  #       with:
  #         distribution: temurin
  #         java-version: "21"

  #     - name: Setup dotnet
  #       uses: actions/setup-dotnet@v5
  #       with:
  #         dotnet-version: 8.0.300

  #     - name: Cache NuGet
  #       uses: actions/cache@v4
  #       with:
  #         path: ~/.nuget/packages
  #         key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
  #         restore-keys: |
  #           ${{ runner.os }}-nuget-

  #     - name: Instalar SonarScanner
  #       run: dotnet tool install --global dotnet-sonarscanner

  #     - name: Restore
  #       working-directory: ./src
  #       run: dotnet restore Review-Filmes.sln

  #     - name: Build e análise
  #       working-directory: ./src
  #       run: |
  #         export PATH="$PATH:/home/runner/.dotnet/tools"
  #         dotnet sonarscanner begin \
  #           /k:"dev-review-filmes" \
  #           /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}" \
  #           /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
  #         dotnet build Review-Filmes.sln --no-restore
  #         dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

  #     - name: Quality Gate
  #       uses: sonarsource/sonarqube-quality-gate-action@master
  #       id: sonarqube-quality-gate-check
  #       env:
  #         SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  #       with:
  #         scanMetadataReportFile: ./src/.sonarqube/out/.sonar/report-task.txt

  #     - name: Exibir status
  #       if: ${{ always() }}
  #       run: echo "Quality Gate falhou na etapa ${{ steps.sonarqube-quality-gate-check.outputs.status }}"

  ci:
    name: Build e Push Dev
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs:
      - unit-testes
      - integration-testes
      # - sonarqube

    outputs:
      image_tag: ${{ steps.meta.outputs.image_tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.0.300

      - name: Cache NuGet
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore
        working-directory: ./src
        run: dotnet restore Review-Filmes.sln

      - name: Build
        working-directory: ./src
        run: dotnet build Review-Filmes.sln --no-restore

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.ARN_ROLE }}

      - name: Login no ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Definir tag curta
        id: meta
        run: |
          SHORT_SHA="${{ inputs.image_tag }}"
          SHORT_SHA="${SHORT_SHA::7}"
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
          echo "image_tag=$SHORT_SHA" >> $GITHUB_OUTPUT

      - name: Build da imagem
        uses: docker/build-push-action@v6
        with:
          context: ./src
          file: ./src/Review-Filmes.Web/Dockerfile
          load: true
          push: false
          tags: |
            ${{ vars.ID_ACCOUNT }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ vars.STAGE }}-review-filmes:${{ env.SHORT_SHA }}
            ${{ vars.ID_ACCOUNT }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ vars.STAGE }}-review-filmes:latest

      - name: Trivy image scan
        uses: aquasecurity/trivy-action@0.23.0
        with:
          scan-type: image
          image-ref: ${{ vars.ID_ACCOUNT }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ vars.STAGE }}-review-filmes:${{ env.SHORT_SHA }}
          format: sarif
          output: trivy-docker-result.sarif
          severity: "UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL"


      - name: Upload SARIF para S3
        if: always()
        run: |
          aws s3 cp trivy-docker-result.sarif \
            s3://${{ secrets.BUCKET_PATH }}/dev/sast/review-filmes-${{ env.SHORT_SHA }}.sarif

      - name: Push da imagem
        run: |
          docker push ${{ vars.ID_ACCOUNT }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ vars.STAGE }}-review-filmes:${SHORT_SHA}
          docker push ${{ vars.ID_ACCOUNT }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ vars.STAGE }}-review-filmes:latest