name: Pipeline CI/CD

run-name: Pipeline CI/CD executada por ${{ github.actor }} em ${{ github.ref_name }}

permissions:
  contents: read
  id-token: write
  security-events: write
  packages: read

on:
  pull_request:
    branches:
      - develop
      - main
    types:
      - closed
    paths-ignore:
      - "k8s/deploy/dev/**"
      - "k8s/deploy/prd/**"

concurrency:
  group: cicd-${{ github.workflow }}-${{ github.event.pull_request.base.ref || github.ref }}
  cancel-in-progress: true

jobs:
  ci-dev:
    name: ci-dev
    if: >
      github.event.pull_request.merged == true &&
      github.event.pull_request.base.ref == 'develop' &&
      github.actor != 'github-actions[bot]'
    uses: wallafidevops/desafio-actions-eks-kustomize-2026/.github/workflows/ci.yml@develop
    with:
      environment: dev
      image_tag: ${{ github.event.pull_request.head.sha }}
    secrets: inherit

  cd-dev:
    name: cd-dev
    if: >
      github.event.pull_request.merged == true &&
      github.event.pull_request.base.ref == 'develop' &&
      github.actor != 'github-actions[bot]'
    needs: [ci-dev]
    uses: wallafidevops/desafio-actions-eks-kustomize-2026/.github/workflows/cd.yml@develop
    with:
      environment: dev
      image_tag: ${{ needs.ci-dev.outputs.image_tag }}
    secrets: inherit

  validate-prod:
    name: validate-prod
    if: >
      github.event.pull_request.merged == true &&
      github.event.pull_request.base.ref == 'main' &&
      github.actor != 'github-actions[bot]'
    uses: wallafidevops/desafio-actions-eks-kustomize-2026/.github/workflows/validate-prod.yml@main
    secrets: inherit

  promote-prod:
    name: promote-prod
    if: >
      github.event.pull_request.merged == true &&
      github.event.pull_request.base.ref == 'main' &&
      github.actor != 'github-actions[bot]'
    needs: [validate-prod]
    uses: wallafidevops/desafio-actions-eks-kustomize-2026/.github/workflows/promote-prod.yml@main
    with:
      image_tag: ${{ needs.validate-prod.outputs.image_tag }}
    secrets: inherit

  cd-prod:
    name: cd-prod
    if: >
      github.event.pull_request.merged == true &&
      github.event.pull_request.base.ref == 'main' &&
      github.actor != 'github-actions[bot]'
    needs: [promote-prod]
    uses: wallafidevops/desafio-actions-eks-kustomize-2026/.github/workflows/cd.yml@main
    with:
      environment: prod
      image_tag: ${{ needs.promote-prod.outputs.image_tag }}
    secrets: inherit