name: Promote Image to Prod

on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string
    outputs:
      image_tag:
        description: "Tag promovida"
        value: ${{ jobs.promote.outputs.image_tag }}
    secrets:
      ARN_ROLE:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  promote:
    name: Promover imagem para prod
    runs-on: ubuntu-latest
    environment: prod
    timeout-minutes: 15

    outputs:
      image_tag: ${{ steps.meta.outputs.image_tag }}

    steps:
      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.ARN_ROLE }}

      - name: Definir tag
        id: meta
        run: |
          IMAGE_TAG="${{ inputs.image_tag }}"
          test -n "$IMAGE_TAG" || { echo "image_tag vazio"; exit 1; }
          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Obter manifesto da imagem de dev
        run: |
          aws ecr batch-get-image \
            --repository-name dev-review-filmes \
            --image-ids imageTag="${IMAGE_TAG}" \
            --query 'images[0].imageManifest' \
            --output text > image-manifest.json

          test -s image-manifest.json || { echo "Manifesto não encontrado."; exit 1; }

      - name: Promover imagem para o ECR prod
        run: |
          aws ecr put-image \
            --repository-name prd-review-filmes \
            --image-tag "${IMAGE_TAG}" \
            --image-manifest file://image-manifest.json

          aws ecr put-image \
            --repository-name prd-review-filmes \
            --image-tag latest \
            --image-manifest file://image-manifest.json