name: Validate Prod Promotion

on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string
    outputs:
      image_tag:
        description: "Tag curta validada"
        value: ${{ jobs.validate.outputs.image_tag }}

permissions:
  id-token: write
  contents: read

jobs:
  validate:
    name: Validar imagem para promoção
    runs-on: ubuntu-latest

    outputs:
      image_tag: ${{ steps.meta.outputs.image_tag }}

    steps:
      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.ARN_ROLE }}

      - name: Definir tag curta
        id: meta
        run: |
          SHORT_SHA="${{ inputs.image_tag }}"
          SHORT_SHA="${SHORT_SHA::7}"
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
          echo "image_tag=$SHORT_SHA" >> $GITHUB_OUTPUT

      - name: Validar existência da imagem no ECR dev
        run: |
          aws ecr describe-images \
            --repository-name dev-review-filmes \
            --image-ids imageTag="${SHORT_SHA}" \
            --region "${{ vars.AWS_REGION }}"